<?php 
$path='';
require "ohcsite/webbodyheader.php" ?>
<div class="container">
	<div id="heading" class="container">
		<h1>African Americans in Ohio</h1>
	</div>
	<div id="localnav" class="container">
		<ul><li><a href="http://www.ohiohistory.org/collections--archives/archives-library">Library/Archives Home</a></li></ul>
	</div><br>
	<div id="altinstructions" class="container">
		<p> A listing of collections in Ohio based on the subject of African Americans in Ohio.
		</p>
	</div>
	<div id="maincontent" class="container">
	<div class="maincontent">
	<p>
	<!--<dt><b><a href="http://dbs.ohiohistory.org/africanam"> African American Experience in Ohio, 1850-1920</a></b></dt>!-->
	<dt><b><a href="http://www.ohiomemory.org/cdm/landingpage/collection/p15005coll34">National Afro-American Museum and Cultural Center (NAAMCC)</a></dt></b>
	
	<blockquote cite="http://www.ohiomemory.org/cdm/landingpage/collection/p15005coll34">The National Afro-American Museum and Cultural Center near Dayton aims to educate the public about African American history and culture from African origins to the present through a variety of programs, including museum exhibits, research and publications, visiting scholars, oral and visual history and adult and children's educational activities.</blockquote>
 
<dt><b><a href="http://www.ohiomemory.org/cdm/landingpage/collection/siebert">Siebert Collection</a></b></dt>
<blockquote cite="http://www.ohiomemory.org/cdm/landingpage/collection/siebert">The Wilbur H. Siebert Collection contains correspondence, notes, manuscripts, student papers, maps, and photographs related to the Underground Railroad. Research material includes the responses generated by his seven-question survey and copies and notes from a wide variety of sources: books; diaries; letters; photographs; newspaper articles; biographies and memoirs; state, county, and local histories; annual reports; trial records; U.S. and Canadian census reports; legislation; and Congressional speeches. Siebert also conducted interviews with Underground Railroad agents and former fugitive slaves. He organized his research by state and county, eventually binding his notes in volumes according to the location of the Underground Railroad station or activity. The collection contains bound and unbound volumes of Siebert's research.

Over 4,700 items from the collection are digitized here. This material represents all of the Ohio items in the collection. Materials related to other states are available on microfilm. <em>online subscription</em></blockquote>
 
<dt><b><a href="http://www.ohiomemory.org/cdm/search/searchterm/african%20american/field/subjec/mode/all/conn/and/order/nosort">Other resources on African American topics on Ohio Memory</a></b></dt>
 <blockquote cite="http://www.ohiomemory.org/cdm/search/searchterm/african%20american/field/subjec/mode/all/conn/and/order/nosort">Various manuscripts, picture mediums, poems, and records from multiple contributors.</blockquote>

 <dt><b><a href="http://www.ohiohistorycentral.org/w/Category:African_Americans">Ohio History Central, topics on African Americans in Ohio</a></b></dt>
<blockquote cite="http://www.ohiohistorycentral.org/w/Category:African_Americans">An index of hundreds of specific topics related African Americans in Ohio.</blockquote>

</p>
</div>
</div>
<div id="endmaincontent" class="container"></div>

</div>
<?php require "ohcsite/webfooterendbody.php" ?>